### ISSUE TITLE
Enemies (Andy Phillips) FATAL ERROR #10

### ISSUE THREAD

**Issue by jpcompton** [johanberntsson/ozmoo#15]
The Inform 5 (!) game [Enemies](https://ifdb.tads.org/viewgame?id=wazvwtxlf7us44qr) crashes early on in Ozmoo with a FATAL ERROR 10.

Recipe to replicate:

- Run Enemies from a 1581. (error will occur with or without REU use, so pick your poison--REU or warp mode recommended because despite being I5, Enemies runs slowly from disk!)
- Z until the cyclist appears. Examine cyclist. Z until the phone rings.
- Answer phone
- Experience FATAL ERROR: 10.

[enemies_ozmoo.zip](https://github.com/johanberntsson/ozmoo/files/5069716/enemies_ozmoo.zip)
<img width="1046" alt="Screen Shot 2020-08-13 at 9 39 52 AM" src="https://user-images.githubusercontent.com/51372049/90148930-857af380-dd49-11ea-8c41-9313c7c32bc7.png">

**Comment by fredrikr** [comment]
Fixed in Ozmoo 3.5.
