### ISSUE TITLE
Benchmark seems to be broken in Ozmoo 4.3

### ISSUE THREAD

**Issue by ZornsLemma** [johanberntsson/ozmoo#16]
With commit 7b59ac8eb830b6a33169083ef3ddb5a0ac3af410, the benchmark seems to be broken. It works fairly well but then goes wrong around move 410, as shown in the attached screenshot.

I noticed this while porting the recent changes to the Acorn, but I've done what I believe is a clean build of the commit mentioned above and run it under VICE and it seems to exhibit a similar problem. Please double check this before trusting this bug report though!
![Screenshot at 2020-09-30 01-03-18](https://user-images.githubusercontent.com/7988240/94629063-9b248800-02b9-11eb-88a1-d481f9c05d5a.png)

**Comment by johanberntsson** [comment]
I can confirm that things go wrong, but I get another error message (This story can't understand the word "7" when you use it in that way, or similar). In any case things go wrong when numbers are used. We'll investigate and fix the problem.

**Comment by johanberntsson** [comment]
It actually breaks already in commit 4311830c822849a865838a37dbfdf70f98813d50
Fixed bugs:
- @tokenise could use arbitrary value for parameter "flag" if it wasn't supplied.
- @tokenise didn't skip words the way it should if parameter "flag" was set. (which stopped Beyond Zork from recognizing any commands).

**Comment by fredrikr** [comment]
Fixed in 4.4.
