### ISSUE TITLE
Pressing ENTER at the prompt repeats the last command

### ISSUE THREAD

**Issue by ZornsLemma** [johanberntsson/ozmoo#17]
You can see this in the attached screenshot of Hollywood Hijinx; I did "LOOK" (which has scrolled off the screen) and then just pressed RETURN (the "empty" prompt about 1/3 of the way down the screen) and it was interpreted as a "LOOK" instead of giving a "[Beg pardon?]" message as it used to.

I think this may be something to do with the commented out code just after .parsing_done in text.asm, but I haven't dug too deeply into this.

![Screenshot at 2020-10-16 23-48-05](https://user-images.githubusercontent.com/7988240/96320370-1a2ff500-100a-11eb-8e59-c44f191989c1.png)

(I am seeing this with commit 183b8e9b248ce32fe681bf49b367022f4b309714.)

**Comment by johanberntsson** [comment]
Thanks for the report. Your guess was correct, and it has now been fixed. (We are changing memory access to make better Plus/4 and C128 ports)

**Comment by ZornsLemma** [comment]
Great, thanks! The memory access changes look quite cool, but I'm holding back on trying to merge them until it's all settled down...

**Comment by johanberntsson** [comment]
Good idea to wait a bit. We're only halfway yet.
