### ISSUE TITLE
Error when compiling with custom fonts

### ISSUE THREAD

**Issue by kaelhem** [johanberntsson/ozmoo#19]
Hello,
I'm trying to compile a zcode file with the online tool available on microheaven.com.
There's no problem with the default system font (english), but selecting the "French / French system font" (or another one), it throws an error : 
```sh
ERROR: Custom fonts are currently not supported for this target platform.
```
The behavior is the same with z3 and z5 files.

I've already used this tool few months ago, and it was working properly, so I think things have changed.
Do I need to do something special to enable custom fonts?

Thanks!

**Comment by fredrikr** [comment]
Fixed. Thanks for reporting!

**Comment by kaelhem** [comment]
Thanks for your quick feedback! You're awesome :)
