### ISSUE TITLE
Typing PETSCII Graphics Characters is allowed, but immediately crashes

### ISSUE THREAD

**Issue by everyfan** [johanberntsson/ozmoo#2]
These should be prevented from being typed, like in the later Infocom C64 interpreter.

Incidentally, in the original Infocom C64 interpreter, you can actually type them, and it'll say something to the effect of "I don't understand the word so-and-so," where so-and-so is a character the Z Machine is not supposed to be able to input or output; and yet it does! How on Earth that happens is beyond me.

**Comment by fredrikr** [comment]
Thanks for the report!

The Ozmoo interpreter isn't fully functional yet. This far, we are working with a ToDo-list in a file, holding tasks we need to deal with, bugs and missing features alike. 

We were aware of this limitation, but hadn't written it down in the ToDo-list yet. Now it's there.

**Comment by fredrikr** [comment]
Fixed in commit 09433d8 .
