### ISSUE TITLE
Support Turbo mode on Ultimate64

### ISSUE THREAD

**Issue by shifters67** [johanberntsson/ozmoo#20]
Apologies this is not an issue - more a request

Could Ozmoo support the ultimate 64 turbo mode to allow playing inform 6 and 7 games?

Here is a link https://1541u-documentation.readthedocs.io/en/latest/config/turbo_mode.html

As there are a lot of those boards out is this possible?

thanks

Shifters

**Comment by oemsysadm** [comment]
Does turbo mode set to "manual" not just speed it up?

**Comment by jpcompton** [comment]
Works for me in both ancient (3.4) and current (13.1) Ozmoo.

**Comment by fredrikr** [comment]
jcompton's advice to run Ozmoo games at full speed on the Ultimate 64:

Set SuperCPU Detect to Disabled, because otherwise Ozmoo's integrated SCPU checker will detect it and turn off REU access, which one doesn't want. Other than that, it seems to Just Work.

Closing issue.
