### ISSUE TITLE
ClairsysOzmoo-Regular-DE.fnt has reverse Ë instead of reverse Ö

### ISSUE THREAD

**Issue by KarolS** [johanberntsson/ozmoo#35]
In ClairsysOzmoo-Regular-DE.fnt, 0x5B is Ö, but 0xDB is for some reason Ë.

Other German fonts don't have that feature.
![obraz](https://user-images.githubusercontent.com/1790750/115285792-95f03300-a14e-11eb-9ba1-4502293eddb1.png)

**Comment by johanberntsson** [comment]
Thanks, fixed in release 7.
