### ISSUE TITLE
Suggestion for changing error message on wrong color index

### ISSUE THREAD

**Issue by demesos** [johanberntsson/ozmoo#37]
The command line options for setting colors give an "Unknown option: " response if the color is outside the range of the Z-code palette. I made the mistake of using C64 color indices instead of the Z-code numbers and was confused by "Unknown option: -sc:15", because it gave me the idea that the option "-sc" is wrong. A feedback like "Color index for -sc is out of range, please be sure to use the Z-code palette" would be more helpful.

**Comment by johanberntsson** [comment]
Thanks. I've committed this change.
