### ISSUE TITLE
Micro-optimisation opportunity in .read_global_var

### ISSUE THREAD

**Issue by ZornsLemma** [johanberntsson/ozmoo#41]
In zmachine.asm for the non-SLOW case, .read_global_var does approximately:
```
    cmp #128
    bcs .read_high_global_var
    asl
    xxx
.read_high_global_var
    asl
    yyy
```
That can be rewritten:
```
    asl
    bcs .read_high_global_var
    xxx
.read_high_global_var
    yyy
```
saving three bytes and two cycles.

To make the SLOW case work I think it's enough to add 'ror' just before 'jsr z_get_low_global_variable_value', or it would be possible to play further conditional assembly games to retain the existing code as-is in the SLOW case.

If it weren't for SLOW I'd suggest this is a small but worthwhile improvement - a small size/speed gain and no real loss in readability. With the SLOW case to be handled I'm not too sure, so I thought I'd raise this issue and see what you thought.

**Comment by ZornsLemma** [comment]
PS The same thing can be done in .write_global_var

**Comment by fredrikr** [comment]
Thanks, saving two clock cycles in code that is accessed so often is definitely a good idea.
