### ISSUE TITLE
VIC20 port using extra RAM cartridge?

### ISSUE THREAD

**Issue by root42** [johanberntsson/ozmoo#42]
I love ozmoo, and am very happy that it works on the C64 and C16 (with 64K upgrade). 

Would it be feasible to make a VIC20 port as well? Given e.g. a 32K or 35K RAM expansion? Or is that not enough for the interpreter to run? I think the Penultimate+ Cartridge provides 35K of RAM for a total of 40K, most of which should be available.

Thank you for your great effort anyway, even if it is not possible. I know that bitshifter's Z machine interpreter can target the VIC20, but I haven't tried it yet and am not sure if it is limited to certain games.

**Comment by fredrikr** [comment]
BitShifter's interpreter should at least be able to run any reasonable z3 game.

I think BitShifter's interpreter is smaller and thus a better fit for a machine with so little memory.

**Comment by Kroc** [comment]
Another reason to consider ROM versions of Ozmoo? A cartridge ROM with a RAM expansion would have little trouble running games, although I can't speak of a desire to use the VIC20's 22-column screen. Maybe even that could be improved using a bitmap mode screen, assuming plenty of RAM was available with most of the game in ROM.

**Comment by root42** [comment]
Cartridge would be great. 40x25 seems to be possible with some RAM usage: https://techtinkering.com/articles/40-columns-in-basic-on-the-commodore-vic-20/

**Comment by johanberntsson** [comment]
The cartridge solution is not a magic bullet and to using all available memory efficiently will require banking, making the code more complicated. It is of course possible to do, but we have currently no plans doing a VIC-20 port in the main Ozmoo repository. However, Ozmoo is open source so anyone can add such functionality and submit a pull request, or maintain Ozmoo for VIC-20 in a new fork (similar to the Acorn version of Ozmoo). We welcome such initiatives.
