### ISSUE TITLE
Character display instead of a line feed for French fonts

### ISSUE THREAD

**Issue by auraes** [johanberntsson/ozmoo#43]
With the French system font in v5, Ozmoo displays a '↑' character instead of a line break:
![bugLF](https://user-images.githubusercontent.com/13295953/147277111-75f8f8e4-dac3-41c0-9c14-e7f9991ef6ac.png)

**Comment by fredrikr** [comment]
I can't reproduce this with the games I've tried. Which game did you see this in?

**Comment by auraes** [comment]
This seems to happen only with my French translation of the library.
With the French translation:
![screen_fr](https://user-images.githubusercontent.com/13295953/147529804-4d0592c3-1aee-4915-b67c-e733897c75b5.png)
Without:
![screen2](https://user-images.githubusercontent.com/13295953/147529812-decf4701-3ba7-4fe8-80c0-0b794ae90965.png)
[bug.tar.gz](https://github.com/johanberntsson/ozmoo/files/7782918/bug.tar.gz)

**Comment by auraes** [comment]
The issue seems to come from the use of Zcharacter in my global.h file header. By removing this part of the code, I don't have the issue.
```
! Part of PunyInform, a standard library for writing interactive fiction using Inform 6.
!
System_file;

!FRENCH
#IfV5;
! treize emplacements disponibles ; il manque 'ä' 'ü' 'ÿ' 'ö' 'æ'
Zcharacter 'à';
Zcharacter 'â';
Zcharacter 'ç';
Zcharacter 'è';
Zcharacter 'é';
Zcharacter 'ê';
Zcharacter 'ë';
Zcharacter 'î';
Zcharacter 'ï';
Zcharacter 'ô';
Zcharacter 'œ';
Zcharacter 'ù';
Zcharacter 'û';
#EndIf;
```

**Comment by auraes** [comment]
With the original English library:
I added !% -Cu in the header of minimal.inf as well as my Zcharacter definitions in the header of global.h.
I converted this way for ozmoo :  `ruby make.rb -cm:fr -f system-FR.fnt minimal.z5` 
![bug](https://user-images.githubusercontent.com/13295953/147541084-8a2b14f3-0a8b-4b4a-af12-0fbdd24416b6.png)

**Comment by fredrikr** [comment]
I think I understand what's happening. If you could supply me with a story file that exhibits this problem, it would be helpful.

**Comment by auraes** [comment]
It's all in there: [bug.tar.gz](https://github.com/johanberntsson/ozmoo/files/7783975/bug.tar.gz)

**Comment by fredrikr** [comment]
Fixed. Thanks for reporting and helping out.
