### ISSUE TITLE
Reverting to default color in dark mode

### ISSUE THREAD

**Issue by oemsysadm** [johanberntsson/ozmoo#48]
When changing color back to the "default colour" (1) with @set_colour in dark mode, it reverts colors to what they are set to in normal/light mode, rather than the current color mode.

This makes dark mode difficult/impossible to use in a game that employs different colors.

**Comment by fredrikr** [comment]
That's quite an oversight on our behalf. Thanks for pointing it out. Fixed in Ozmoo 11.11.
