### ISSUE TITLE
Drive selection with save/restore

### ISSUE THREAD

**Issue by oemsysadm** [johanberntsson/ozmoo#49]
When you first save or restore, Ozmoo lets you select a drive. It remembers this drive selection, which is good, but unfortunately also if you selected the wrong drive there are no "do overs" that I can see. No way to change the drive for future saves or restores.

Maybe allow save/restore to explicitly set a default file/drive, like 'save to drive 9 with comment "my new save"' or "restore file 5 from drive 11", etc., and do that again next time save or restore is called on its own with simple Y/N verification?

I don't know if it would also be feasible to skip drive selection if only one drive is detected available.

**Comment by fredrikr** [comment]
Fixed in 11.30.

Press Ctrl-D to make Ozmoo forget the device selection.
