### ISSUE TITLE
Italian accents not all displayed

### ISSUE THREAD

**Issue by Technotron-HF** [johanberntsson/ozmoo#58]
I'm writing an adventure in Italian but I see that the fonts don't display all the accented characters like à and ù for example.
So what tools are necessary to create my own .fnt fonts? I would like to add the missing characters.

**Comment by fredrikr** [comment]
à and ù are displayed.

![image](https://github.com/johanberntsson/ozmoo/assets/1001548/a1c738f5-0ad2-47a2-8c2a-a330cae2209c)

Please provide details on what you've tried that didn't work.

**Comment by Technotron-HF** [comment]
Thanks for your reply.

For making the accent ù and à I use the code @'u and @'a in the inform6 program.
But these characters are not displayed in the c64 compiled program by ozmoo.

Furthermore, the simple "a" letter is not displayed too in the object description available in a room. As you can see from this screenshot the line that should read "Puoi vedere una pergamena qui" is shown as "Puoi vedere un'pergamena qui".

![vice-screen](https://github.com/johanberntsson/ozmoo/assets/135476383/4548d61f-3320-4ff1-aaf7-c7212a5a950f)

**Comment by fredrikr** [comment]
What does your command to compile look like, and what compiler directives do you give in the source code?

Which Zcharacter directives do you give in the source code?

I suggest you write your source code as UTF-8 text and use -Cu to compile it - then you can write the accented characters just the way they are, without resorting to @-codes.

If you use a regular single quote when writing @'a, you get an a with an acute accent, and this character is not present in the Italian font. This would typically mean that the character isn't printed at all by Ozmoo.

**Comment by Technotron-HF** [comment]
my command to compile is like follow:
inform +language_name=italian file.inf file.z5

In the source code I import these:
 Include "Parser";
 Include "VerbLib";
 Include "replace";
...
Include "ItalianG";


if I compile like follow I get an error (-C must be followed by 0 to 9)
inform +language_name=italian -Cu file.inf file.z5

-C must be followed by 0 to 9

**Comment by fredrikr** [comment]
You need to upgrade the Inform compiler. The -Cu option appeared in Inform 6.33. If possible, get version 6.41. You will find it at https://ifarchive.org/indexes/if-archive/infocom/compilers/inform6/

**Comment by fredrikr** [comment]
Another interesting question is: Does your game work perfectly in Frotz (e.g. Windows Frotz)?

**Comment by Technotron-HF** [comment]
Unluckily I am not able to run an updated version of inform. I'm stuck with version 6.31 on my Linux machine.

With Frotz for Linux the compiled z5 program runs smoothly.

**Comment by fredrikr** [comment]
Compiling Inform from source on Linux is dead simple.

1. Download the source code ( https://ifarchive.org/if-archive/infocom/compilers/inform6/source/inform641_source.zip )
2. Unpack the source code in a folder. Let's say you choose ~/inform641_source
3. `cd ~/inform641_source`
4. `gcc *.c -o inform`

You now have a new binary. Try:
```
./inform
```

**Comment by fredrikr** [comment]
What has most likely happened is that the Inform compiler has chosen to change which characters are in the extended ZSCII range, and in which positions. This is perfectly legal to do, and a modern interpreter such as Frotz will happily handle it. Ozmoo is a bit more constrained, and will not handle a custom set of extended ZSCII characters. If you write your source code using UTF-8 and compile using -Cu, Inform shouldn't just stick to the default set of extended ZSCII characters, and all should be fine.

**Comment by Technotron-HF** [comment]
I have compiled inform641 source. But when I use the newly compiled version I get this error message when I try to compile the .inf code:
Error:  No such constant as "THE__TX"

**Comment by Technotron-HF** [comment]
I have discovered that ozmoo can print the Italian accented characters if I give the unicode code in the source code like this:

à	@{e0}
è	@{e8}
ì	@{ec}
ò	@{f2}
ù	@{f9}

So, for example, if I write in the source:
print "libertà"
I should write in the source code:
print "libert@{e0}"

...and it works

**Comment by fredrikr** [comment]
Italian Inform was made to be used with Inform library 6/10. I suspect you're trying to use it with the latest library version, and this causes the error mentioning that THE__TX doesn't exist.

As the creator of Swedish Inform, I can tell you that library translations are highly unlikely to work with newer versions of the library without putting in some serious work to update the translation first.

Library 6/10 is available at https://ifarchive.org/indexes/if-archive/infocom/compilers/inform6/library/old/

**Comment by fredrikr** [comment]
Note that you have to add ".h" at the end of each filename in library 6/10, except relnote and relnote2. I.e. rename "parser" to "parser.h" etc.

**Comment by Technotron-HF** [comment]
I'm using inform 6.41 with the old libraries and it works now. Also the -Cu option works.

**Comment by fredrikr** [comment]
Glad to hear it! Closing issue.
