### ISSUE TITLE
Strange line break with @set_colour.

### ISSUE THREAD

**Issue by auraes** [johanberntsson/ozmoo#6]
Hello,
there's something weird going on with @set_colour in my code. There's a line break after the parentheses when there shouldn't be. But it only happens on the tenth line. 
If I comment out and disable the @set_colour instructions, everything is fine.

> Without @set_colour:
> 9) Quam ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo, ut ais, sapientissimum iudicavit.
> 10) Quam ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo, ut ais, sapientissimum iudicavit.

> With @set_colour :
> 9) Quam ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo, ut ais, sapientissimum iudicavit.
> 10)
> Quam ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo, ut ais, sapientissimum iudicavit.

```
Constant CLR_DEFAULT 1;
Constant CLR_BLUE 6;
[ Main   key i msg;
   msg = "Quam ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo, 
   ut ais, sapientissimum iudicavit.";
   for (i=1 : i<15 : i++) {
      new_line;
      @set_colour CLR_BLUE CLR_DEFAULT;
      print i, ")";
      @set_colour CLR_DEFAULT CLR_DEFAULT;
      print " ", (string) msg; 
   }
   @read_char 1 ->key;
];
```

**Comment by fredrikr** [comment]
Fixed.
