### ISSUE TITLE
Target request: Commander X16

### ISSUE THREAD

**Issue by DavidGriffith** [johanberntsson/ozmoo#61]
The 8-bit Guy (https://www.the8bitguy.com/) has released his supercharged dream C64 clone, the Commander X16.  Have any of you thought of getting one of those machines and/or adding that machine as a build target?

**Comment by johanberntsson** [comment]
I tried a few years back but ran into problems with bugs in the emulator. It would be nice with a X16 target so we'll give it another try to see if the latest version of the emulator has been improved enough to make this possible. Unfortunately none of us has access to real hardware.

**Comment by DavidGriffith** [comment]
I'll see what I can do myself as well.

For anyone else watching, the emulator is here: https://github.com/x16community/x16-emulator

**Comment by johanberntsson** [comment]
Actually we've already started working on a port. There is a new x16 branch. Far from finished, but we'll get there

**Comment by johanberntsson** [comment]
Release 14 supports X16!
