### ISSUE TITLE
Feature request (with implementation): Optionally convert "x" on input to "examine"

### ISSUE THREAD

**Issue by ZornsLemma** [johanberntsson/ozmoo#65]
I added this as an experimental option to the Acorn port a while ago, and you can see the code (which is probably portable) [around line 1891 in text.asm](https://github.com/ZornsLemma/ozmoo/blob/89a9a2a6e744cb373ef78c5138e0f00e2ade2fa3/asm/text.asm#L1891l). I think this improves the playability of games like Hollywood Hijinx which don't natively support it.

(It's possible - probably even likely - my implementation is sub-optimal, let me know if you have any suggestions.)

**Comment by fredrikr** [comment]
Great suggestion. Added in Ozmoo 14.21.

**Comment by johanberntsson** [comment]
Note that make.rb now activates this by default for all Infocom games that benefit from this option, including a few z4 and z5 games
