### ISSUE TITLE
Micro-optimisation opportunity in "X for examine" code

### ISSUE THREAD

**Issue by ZornsLemma** [johanberntsson/ozmoo#66]
I see you had to replace a beq with a jmp in https://github.com/johanberntsson/ozmoo/commit/387de0f5b48686b4ae8224fb5a63121a8d566f02 to avoid out-of-range branches. (I got hit by this on the Acorn port the other day too.) If you want, you can instead do:
```
	cmp #'.'
.beq_look_for_x
	beq .look_for_x
	cmp #','
	beq .beq_look_for_x
	bne -
```
since performance isn't really a concern here.

**Comment by fredrikr** [comment]
Thanks, we've done this now!
