### ISSUE TITLE
Possible micro-optimisation in screen.asm

### ISSUE THREAD

**Issue by ZornsLemma** [johanberntsson/ozmoo#69]
There are two copies of the following code sequence in screen.asm:
```
	jsr z_get_low_global_variable_value
	stx z_operand_value_low_arr
	sta z_operand_value_high_arr
	jsr z_ins_print_num
```
By moving the first three instructions to immediately before z_ins_print_num (so they can fall through into it), seven bytes can be saved. If the sequence is labelled something like "print_low_global_variable_value" I don't think this even harms readability.

**Comment by fredrikr** [comment]
Good idea, thanks. Done.
