### ISSUE TITLE
Is it possible to configure cursor shape and color?

### ISSUE THREAD

**Issue by hyperbolist** [johanberntsson/ozmoo#7]
In revision 88 of Zork 1 for C64, the one with the grey background and white foreground and black status bar, the cursor is a black underscore.  Is it possible to easily recreate that black underscore cursor in ozmoo's output?

I'm ignorant of C64 programming in general, but I've found some arcane references for low-level cursor handling.  My guess is that the system-provided cursor is not displayed, but its location is tracked and a custom character is displayed in that screen location instead.

**Comment by johanberntsson** [comment]
The standard C64 kernal routines cannot handle status lines, so instead asm/screenkernal.asm implements replacement routines. This means that the documentation you look at doesn't apply. The cursor appearance is currently hard coded in the update_cursor routine in asm/text.asm (by reversing the character under the cursor with the "ora #$80" instruction). We could perhaps make it configurable if it is a demand for that feature, or if you are able to you could compile from source and make adjustments in this routine yourself.

**Comment by hyperbolist** [comment]
Thanks for pointing me to the cursor location.  I'll take it as an exercise to wire it up for configuration.

**Comment by johanberntsson** [comment]
Feel free to send us a patch if you come up with something nice
