### ISSUE TITLE
No line breaks in Wishbringer after save/restore

### ISSUE THREAD

**Issue by root42** [johanberntsson/ozmoo#71]
I am playing Wishbringer using https://ozmoo.online on my C64 with default settings. After doing a save or restore, all text is missing line breaks. Before it was fine. Seems to be Ozmoo 14.4.
A Kung Fu Flash with AR Fastload is in use.

**Comment by fredrikr** [comment]
Thanks for the report! 

Ozmoo uses a *lot* of zeropage locations, and it's expecting them to remain untouched during save/restore operations.

My best guess is that the fastloader writes the value 0 at address $ab, as this would cause just the symptoms you're describing.

**Comment by fredrikr** [comment]
As it turns out, $ab was unsafe to use on C64, Plus/4 and MEGA65 (we used it on all of these platforms).

I've changed it to safer addresses in Ozmoo v14.43, and have updated Ozmoo Online to use the new version of Ozmoo.

**Comment by root42** [comment]
Thanks, @fredrikr for doing the quick update. I recreated the Calypso disk, I guess with the new version. However with AR loaded it still has the same issue. Deactivating AR increases load times massively, obviously, but fixes the issue. So it HAS to do with the AR, but I think the problem is not fixed.

**Comment by fredrikr** [comment]
Which version of Action Replay are you using?

I tried the latest version I could find, in Vice, but can't get it to work.

**Comment by root42** [comment]
I am using AR 6.0. I think it is easy to find on the web. I put it on my KFF cart and use it for games that are a bit slow. :)

**Comment by fredrikr** [comment]
I did manage to get something to go wrong when using Action Replay 6. Is this what happens to you, with the text just being cut off at the screen edge?

![image](https://github.com/user-attachments/assets/586c4c34-4178-42b2-8e0a-64d7941cd784)

**Comment by root42** [comment]
Yes exactly that!

**Comment by fredrikr** [comment]
Okay fixed it. Apparently  AR uses $a7, which Ozmoo was also using. Switched to using $d8 instead, and now it looks good to me with AR Fastload enabled.

**Comment by fredrikr** [comment]
(I have updated Ozmoo Online too)

**Comment by root42** [comment]
Works perfectly! After recreating the Calypso image and restoring my previous savegame, the text is fixed:

![IMG_6384](https://github.com/user-attachments/assets/58e62943-f10d-445a-9537-90de18f9ecde)

**Comment by fredrikr** [comment]
Great to see it working for you! Thanks for reporting back.
