### ISSUE TITLE
Current version of Ozmoo doesn't overwrite savegames on C64 with 1541

### ISSUE THREAD

**Issue by root42** [johanberntsson/ozmoo#73]
My setup:

- Ozmoo 14.45, Running Sherlock Z5 in two disk mode (Boot + Story)
- C64C
- 1541 as device 8 for boot and story
- 1541-II as device 9 for saves

When saving to device 9 it works just fine, EXCEPT if I try to OVERWRITE an existing game. Sometimes the drive errors out (blinking status LED) and ozmoo reports "save successful". Or it will do the save (takes ~30 seconds or so) and also report success. But on restore, the saves still list the OLD savegame under that slot. Loading said savegame will also result in the old state to be restored. 
Saving to a NEW slot works fine. But as there are only 8 slots this limits usability...

**Comment by fredrikr** [comment]
Thanks a lot for the report. This has been broken since Ozmoo 14.14, which was released seven months ago, but we had no idea it was broken until now. Fixed in 14.46. I updated Ozmoo Online as well.

**Comment by root42** [comment]
Awesome! I will test it out in the next days, when we continue playing Sherlock! Thanks for the very quick support!
