### ISSUE TITLE
Cursor doesn't blink.

### ISSUE THREAD

**Issue by hyperbolist** [johanberntsson/ozmoo#9]
`asm/text.asm` mentions a "blinking cursor" but the cursor does not blink.

It looks like the current timer is only for `Z4PLUS`, and I'm not sure what it's actually used for.

I imagine adding a blinking cursor that works for Z3 will require adding another timer to count jiffies and a means to track the current cursor blink state.  Looks like `$CD` is a sensible place to count down jiffies and `$CF` is a sensible place to track current cursor blink state according to https://gist.github.com/cbmeeks/4287745eab43e246ddc6bcbe96a48c19  And when toggling cursor blink state I'll just call our own `turn_on_cursor` and `turn_off_cursor`.

Does that seem sensible or am I way off track?

**Comment by johanberntsson** [comment]
We decided against it since we wanted to keep the code as small as possible, and it didn't feel necessary. As you say it can be implemented by checking the jiffies, but there will be some cost in a new timer and other tests.

**Comment by johanberntsson** [comment]
If you feel that you want a blinking cursor then go for it, but it shouldn't be included by default. We could of course add an option to make.rb which would compile in blinking cursor support if requested.

**Comment by hyperbolist** [comment]
Ok, I'll see what kind of progress I can make and only conditionally include it if requested via make.rb.

**Comment by johanberntsson** [comment]
Oh, btw. I saw you asked about the current timer. It is for timed input in Infocom games such as Border Zone. These games provide a callback to the read opcode so that things may happen (guards moving around etc.) even if the game is waiting for user input.

**Comment by johanberntsson** [comment]
Blinking support that fits in the current design has been added. I used the same -cb:n syntax you suggested in your patch. Not completely tested yet, but seems to work

**Comment by johanberntsson** [comment]
Cursor blinking has been added and will appear in the next release.

**Comment by hyperbolist** [comment]
Looks awesome, thanks!  It does indeed work with the default block cursor shape.  Speed 7 seems "normal".  But it does not work for me with the underscore or line cursor shapes.  I believe I saw this exact behavior while I was working on my version, where the "blink off" was only actually visible while typing.  I'll see if I can migrate my solution for that into your blink implementation.

**Comment by johanberntsson** [comment]
Good to head that it works for you. I'm sure it can be improved further, so
if you find anything then please send a patch or let me know.

/Johan
